// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-news.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_news_default = defineTool({
  name: "list_news",
  title: "List news articles",
  description: "List recently published Peterborough Athletic FC news articles (title, slug, excerpt, publish date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of articles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("news_articles").select("title, slug, excerpt, published_at, category, author_name").eq("is_published", true).order("published_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_events_default = defineTool2({
  name: "list_events",
  title: "List upcoming club events",
  description: "List upcoming Peterborough Athletic FC club events (title, start time, location).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("Max number of events to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabase.from("club_events").select("title, description, start_time, end_time, location").gte("start_time", nowIso).order("start_time", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-player-of-the-match.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_player_of_the_match_default = defineTool3({
  name: "list_player_of_the_match",
  title: "List Player of the Match awards",
  description: "List recent Peterborough Athletic FC Player of the Match awards.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Max number of awards to return."),
    age_group: z3.string().optional().describe("Optional age group slug filter, e.g. 'u9s'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, age_group }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("player_of_the_match").select("player_name, age_group, team_name, award_date, match_description, reason, shirt_number").order("award_date", { ascending: false }).limit(limit);
    if (age_group) query = query.eq("age_group", age_group);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { awards: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "pafc-mcp",
  title: "Peterborough Athletic FC",
  version: "0.1.0",
  instructions: "Read-only tools for Peterborough Athletic FC ('The Lions'). Use `list_news` for recent published articles, `list_events` for upcoming club events, and `list_player_of_the_match` for recent POTM awards.",
  tools: [list_news_default, list_events_default, list_player_of_the_match_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
