
ALTER TABLE public.tournament_teams
  ADD COLUMN IF NOT EXISTS manual_played INTEGER,
  ADD COLUMN IF NOT EXISTS manual_won INTEGER,
  ADD COLUMN IF NOT EXISTS manual_drawn INTEGER,
  ADD COLUMN IF NOT EXISTS manual_lost INTEGER,
  ADD COLUMN IF NOT EXISTS manual_gf INTEGER,
  ADD COLUMN IF NOT EXISTS manual_ga INTEGER,
  ADD COLUMN IF NOT EXISTS manual_points INTEGER;
